/**
* @file   StringDefine.h
* @brief  文字列定数
* @author Syota Tachikawa
*/

#ifndef ___STRINGDEFINE_H
#define ___STRINGDEFINE_H

#define DECISION_SE						"Data/Sound/SE/decision.wav"
#define CURSOL_SE						"Data/Sound/SE/cursor.wav"
#define CUTIN_SE						"Data/Sound/SE/cutin.wav"
#define FLAME_HIT_SE					"Data/Sound/SE/flame_hit.wav"
#define BLADE_SE						"Data/Sound/SE/slash.wav"
#define MAGICCIRCLE_SE					"Data/Sound/SE/magiccircle.wav"
#define FLAME_SE						"Data/Sound/SE/flame.wav"
#define FLAMECOLLIDE_SE					"Data/Sound/SE/flame2.wav"
#define SWORDSWING_SE					"Data/Sound/SE/swordswing.wav"
#define SWORDBLOW_SE					"Data/Sound/SE/blow.wav"
#define EXTRASKILL_SE					"Data/Sound/SE/exskill.wav"
#define BOMB_SE							"Data/Sound/SE/bomb.wav"
#define DOWN_SE							"Data/Sound/SE/down.wav"
#define SETUPMOTION_SE					"Data/Sound/SE/setupmotion.wav"
#define OFFSET_SE						"Data/Sound/SE/offset.wav"
#define GUARD_SE						"Data/Sound/SE/guard.wav"
#define CHEER_SE						"Data/Sound/SE/cheer.wav"
#define CHEER2_SE						"Data/Sound/SE/cheer2.wav"
#define LAUGH_SE						"Data/Sound/SE/laugh.wav"
#define VSSWITCH_SE						"Data/Sound/SE/sceneswitch.wav"
#define VERSUS_SE						"Data/Sound/SE/gameversus.wav"
#define KO_SE							"Data/Sound/SE/ko.wav"

#define TITLE_BGM						"Data/Sound/BGM/Title.wav"
#define BATTLE_BGM						"Data/Sound/BGM/Battle.wav"
#define CHARACTERSELECT_BGM				"Data/Sound/BGM/characterselect.wav"
#define RESULT_BGM						"Data/Sound/BGM/result.wav"

#define LILIA_TITLE_VOICE				"Data/Sound/VOICE/リリア/タイトルコール.wav"
#define LILIA_CHARASELECT_VOICE			"Data/Sound/VOICE/リリア/かしづきなさい、レーヴァテイン.wav"
#define LILIA_CHARASELECTWAIT_VOICE		"Data/Sound/VOICE/リリア/いいわよ、別に貴方に力を貸してあげても.wav"
#define LILIA_BEFOREBATTLE_VOICE		"Data/Sound/VOICE/リリア/負けた方は勝った方に一生服従よ.wav"
#define LILIA_SQUATATTACK_VOICE			"Data/Sound/Voice/リリア/そこっ.wav"
#define LILIA_DASHATTACK_VOICE			"Data/Sound/Voice/リリア/せいっ.wav"
#define LILIA_JUMPATTACK_VOICE			"Data/Sound/Voice/リリア/やっ.wav"
#define LILIA_ATTACKWEAK_VOICE			"Data/Sound/VOICE/リリア/とう.wav"
#define LILIA_ATTACKWEAK_DER_VOICE		"Data/Sound/VOICE/リリア/つらぬけ.wav"
#define LILIA_ATTACKMEDIUM_VOICE		"Data/Sound/VOICE/リリア/あんたに見切れるかしら.wav"
#define LILIA_ATTACKSTRONG_VOICE		"Data/Sound/VOICE/リリア/吹き飛びなさい.wav"
#define LILIA_ATTACKSTRONG_VOICE2		"Data/Sound/VOICE/リリア/消し炭にしてあげるわ.wav"
#define LILIA_ATTACKSPECIAL_VOICE		"Data/Sound/VOICE/リリア/消し炭になりなさい。フレイムバースト.wav"
#define LILIA_ATTACKSPECIAL_VOICE2		"Data/Sound/VOICE/リリア/これで終わりよ.wav"
#define LILIA_ATTACKSPECIAL_VOICE3		"Data/Sound/VOICE/リリア/はあああああ.wav"
#define LILIA_ATTACKSPECIAL_SUCCESS		"Data/Sound/VOICE/リリア/安心しなさい。急所は外してあげたわ.wav"
#define LILIA_ATTACKSPECIAL_PUR_VOICE	"Data/Sound/VOICE/リリア/つらぬけええええ.wav"
#define LILIA_GUARDPRAISE_VOICE			"Data/Sound/VOICE/リリア/いい判断ね.wav"
#define LILIA_SCREAM_VOICE				"Data/Sound/VOICE/リリア/きゃああああ.wav"
#define LILIA_GASP_VOICE				"Data/Sound/VOICE/リリア/喘ぎ.wav"
#define LILIA_GASP_VOICE2				"Data/Sound/VOICE/リリア/喘ぎ３.wav"
#define LILIA_WIN_VOICE					"Data/Sound/VOICE/リリア/大したことなかったわね.wav"
#define LILIA_LOSE_VOICE				"Data/Sound/VOICE/リリア/きゃ、いやああ.wav"
#define LILIA_PASSIVE_VOICE				"Data/Sound/VOICE/リリア/ここからよ.wav"


#define RUNA_CHARASELECT_VOICE			"Data/Sound/VOICE/ルナ/よし、妾の出番だな.wav"
#define RUNA_CHARASELECTWAIT_VOICE		"Data/Sound/VOICE/ルナ/どうした、妾の事が気になるのか.wav"
#define RUNA_BEFOREBATTLE_VOICE			"Data/Sound/VOICE/ルナ/ククク、力が溢れてくるぞ.wav"
#define RUNA_SQUATATTACK_VOICE			"Data/Sound/Voice/ルナ/そこっ.wav"
#define RUNA_DASHATTACK_VOICE			"Data/Sound/Voice/ルナ/逃がすかああああ.wav"
#define RUNA_JUMPATTACK_VOICE			"Data/Sound/Voice/ルナ/やっ.wav"
#define RUNA_ATTACKWEAK_VOICE			"Data/Sound/VOICE/ルナ/せい.wav"
#define RUNA_ATTACKWEAK_DER_VOICE		"Data/Sound/VOICE/ルナ/そこだ.wav"
#define RUNA_ATTACKMEDIUM_VOICE			"Data/Sound/VOICE/ルナ/てええい.wav"
#define RUNA_ATTACKSTRONG_VOICE			"Data/Sound/VOICE/ルナ/吹き飛べ.wav"
#define RUNA_ATTACKSTRONG_VOICE2		"Data/Sound/VOICE/ルナ/漆黒の闇に染まれ.wav"
#define RUNA_ATTACKSPECIAL_VOICE		"Data/Sound/VOICE/ルナ/漆黒の闇に染まれ２.wav"
#define RUNA_ATTACKSPECIAL_VOICE2		"Data/Sound/VOICE/ルナ/妾の一撃、受けてみよ.wav"
#define RUNA_ATTACKSPECIAL_VOICE3		"Data/Sound/VOICE/ルナ/はああああああ.wav"
#define RUNA_ATTACKSPECIAL_SUCCESS		"Data/Sound/VOICE/ルナ/これは妾からのプレゼントだ.wav"
#define RUNA_ATTACKSPECIAL_PUR_VOICE	"Data/Sound/VOICE/ルナ/そこだあああああ.wav"
#define RUNA_GUARDPRAISE_VOICE			"Data/Sound/VOICE/ルナ/妾を欺くことはできんぞ.wav"
#define RUNA_SCREAM_VOICE				"Data/Sound/VOICE/ルナ/きゃああああ.wav"
#define RUNA_GASP_VOICE					"Data/Sound/VOICE/ルナ/喘ぎ.wav"
#define RUNA_GASP_VOICE2				"Data/Sound/VOICE/ルナ/喘ぎ３.wav"
#define RUNA_WIN_VOICE					"Data/Sound/VOICE/ルナ/当然の結果だな.wav"
#define RUNA_LOSE_VOICE					"Data/Sound/VOICE/ルナ/そんな妾の力では.wav"
#define RUNA_PASSIVE_VOICE				"Data/Sound/VOICE/ルナ/やっ.wav"

#endif